name: Global Python Checks

on:
  workflow_call:   # makes this reusable

jobs:
  checks:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: "3.10"

      # 1. ✅ Check required project files exist
      - name: Verify project structure
        run: |
          missing=0
          for file in requirements.txt README.md; do
            if [ ! -f "$file" ]; then
              echo "❌ Missing required file: $file"
              missing=1
            fi
          done
          if [ $missing -ne 0 ]; then
            exit 1
          fi

      # 2. ✅ Check for hardcoded sensitive values
      - name: Scan for hardcoded values
        run: |
          if grep -rE "password|passwd|api[_-]?key|secret|token|AKIA[0-9A-Z]{16}|[0-9]+\.[0-9]+\.[0-9]+\.[0-9]+" . --exclude-dir=.git --include=*.py; then
            echo "❌ Hardcoded secrets or IPs found!"
            exit 1
          else
            echo "✅ No hardcoded values detected."
          fi

      # 3. ✅ Install dependencies if requirements.txt exists
      - name: Install dependencies
        if: exists('requirements.txt')
        run: pip install -r requirements.txt

      # 4. ✅ Run linting (basic style + unused imports check)
      - name: Run flake8 lint
        run: |
          pip install flake8
          flake8 . --count --select=E9,F63,F7,F82 --show-source --statistics

      # 5. ✅ Verify Python files can compile
      - name: Compile Python code
        run: python -m compileall .
